### ISSUE TITLE
아이템 01. 생성자 대신 정적 팩토리 메서드를 고려하자

### ISSUE THREAD

**Issue by peacebestill0314** [AskMePlz/EffectiveJava#1]

**Comment by leechGamer** [comment]
> p.9 두번째, 호출될 때마다 인스턴스를 새로 생성하지는 않아도 된다. 

이 부분 아래 이 [포스팅](https://donghyeon.dev/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%EC%9E%90%EB%B0%94/2020/12/01/%EB%B6%88%ED%95%84%EC%9A%94%ED%95%9C-%EA%B0%9D%EC%B2%B4-%EC%83%9D%EC%84%B1%EC%9D%80-%ED%94%BC%ED%95%98%EC%9E%90/) 보면 이해가 더 쉬울 것 같아요!
