### ISSUE TITLE
아이템 04. 인스턴스화를 막으려거든 private 생성자를 사용하라

### ISSUE THREAD

**Issue by JamieShin0201** [AskMePlz/EffectiveJava#4]

**Comment by dev-jaekkim** [comment]
1️⃣
p26
추상 클래스로 만드는 것으로는 인스턴스화를 막을 수 없다. 
> 이 부분에서 추상 클래스로 인스턴스화를 막는 방법이 궁금합니다!

**Comment by dev-jaekkim** [comment]
2️⃣
p26 
마지막으로, final 클래스와 관련한 메서드들을 모아놓을 때도 사용한다. final 클래스를 상속해서 하위 클래스에 메서드를 넣는 건 불가능하기 때문이다. 

이 부분이 static과 어떤 연관이 있는건지 궁금합니다. 저 말만 보면, 왜 저자가 언급을 했는지 의도가 이해가 안됩니다 ㅠㅠ

**Comment by dev-jaekkim** [comment]
3️⃣
p27 
코드 예시에 Assertion Error를 발생시키는데, 왜 해당 에러를 사용하는지 궁금하니다.  
Assertion Error의 경우, java공식 문서에 따르면, 

![image](https://user-images.githubusercontent.com/67681815/149757506-a367734e-1613-4c4e-af5b-2596670646d7.png)

이렇게 나오는데, 해당 설명만 보면 그냥 참 이라고 예상되는 것이 거짓임을 나타내는 에러정도로 보이는데, 다른 예외처리는 존재하지 않아 해당 예외처리를 쓴 것인지가 궁금합니다. 
https://docs.oracle.com/javase/8/docs/api/

**Comment by JamieShin0201** [comment]
1️⃣
> p26 추상 클래스로 만드는 것으로는 인스턴스화를 막을 수 없다.
> 
> > 이 부분에서 추상 클래스로 인스턴스화를 막는 방법이 궁금합니다!

추상 클래스 생성자를 private 으로 만들어 하위 클래스에서 상위 클래스 생성자를 호출하지 못하도록 해 인스턴스화를 막을 수 있습니다.
```java
public abstract class Person {
    private Person() {
    }
}
```
```java
public class Child extends Person {
    public Child() {
        super(); // Error: 'Person()' has private access
        System.out.println("Child Constructor");
    }
}
```

**Comment by JamieShin0201** [comment]
2️⃣
> p26 마지막으로, final 클래스와 관련한 메서드들을 모아놓을 때도 사용한다. final 클래스를 상속해서 하위 클래스에 메서드를 넣는 건 불가능하기 때문이다.
> 
> 이 부분이 static과 어떤 연관이 있는건지 궁금합니다. 저 말만 보면, 왜 저자가 언급을 했는지 의도가 이해가 안됩니다 ㅠㅠ

final 클래스는 상속을 통해 메서드를 추가할 수 없습니다. 그래서 `정적 메서드와 정적 필드를 담은 클래스`를 만들어 final 클래스에 추가하고 싶은 메서드를 정의한다는 의미 인 것 같습니다.

`String`과 `org.springframework.util` 패키지에 있는 `StringUtils` 라는  클래스가 예시가 되지 않을까 싶어요. 

String: final 클래스
StringUtils: 정적 필드와 정적 메서드만 담은 클래스

**Comment by JamieShin0201** [comment]
3️⃣
> p27 코드 예시에 Assertion Error를 발생시키는데, 왜 해당 에러를 사용하는지 궁금하니다. Assertion Error의 경우, java공식 문서에 따르면,
> 
> ![image](https://user-images.githubusercontent.com/67681815/149757506-a367734e-1613-4c4e-af5b-2596670646d7.png)
> 
> 이렇게 나오는데, 해당 설명만 보면 그냥 참 이라고 예상되는 것이 거짓임을 나타내는 에러정도로 보이는데, 다른 예외처리는 존재하지 않아 해당 예외처리를 쓴 것인지가 궁금합니다. https://docs.oracle.com/javase/8/docs/api/

생성자를 private으로 하더라도 해당 클래스내에서는 호출할 수 있으니 `이 생성자는 호출되서는 안됩니다.`라고 개발자의 의도를 `AssertionError`을 통해 전달하는게 아닌가 싶습니다. 아래 스택오버플로우에 해당 내용에 대한 답변이 있습니다.

참고: https://stackoverflow.com/questions/24863185/what-is-an-assertionerror-in-which-case-should-i-throw-it-from-my-own-code

**Comment by dev-jaekkim** [comment]
> > p27 코드 예시에 Assertion Error를 발생시키는데, 왜 해당 에러를 사용하는지 궁금하니다. Assertion Error의 경우, java공식 문서에 따르면,
> > ![image](https://user-images.githubusercontent.com/67681815/149757506-a367734e-1613-4c4e-af5b-2596670646d7.png)
> > 이렇게 나오는데, 해당 설명만 보면 그냥 참 이라고 예상되는 것이 거짓임을 나타내는 에러정도로 보이는데, 다른 예외처리는 존재하지 않아 해당 예외처리를 쓴 것인지가 궁금합니다. https://docs.oracle.com/javase/8/docs/api/
> 
> 생성자를 private으로 하더라도 해당 클래스내에서는 호출할 수 있으니 `이 생성자는 호출되서는 안됩니다.`라고 개발자의 의도를 `AssertionError`을 통해 전달하는게 아닌가 싶습니다. 아래 스택오버플로우에 해당 내용에 대한 답변이 있습니다.
> 
> 참고: https://stackoverflow.com/questions/24863185/what-is-an-assertionerror-in-which-case-should-i-throw-it-from-my-own-code

아 개발자가 의도하지 않는 상황인 경우에 해당 에러를 발생시킨다고 이해하면 되는군요! 답변 감사합니다!

**Comment by dev-jaekkim** [comment]
> > p26 마지막으로, final 클래스와 관련한 메서드들을 모아놓을 때도 사용한다. final 클래스를 상속해서 하위 클래스에 메서드를 넣는 건 불가능하기 때문이다.
> > 이 부분이 static과 어떤 연관이 있는건지 궁금합니다. 저 말만 보면, 왜 저자가 언급을 했는지 의도가 이해가 안됩니다 ㅠㅠ
> 
> final 클래스는 상속을 통해 메서드를 추가할 수 없습니다. 그래서 `정적 메서드와 정적 필드를 담은 클래스`를 만들어 final 클래스에 추가하고 싶은 메서드를 정의한다는 의미 인 것 같습니다.
> 
> `String`과 `org.springframework.util` 패키지에 있는 `StringUtils` 라는 클래스가 예시가 되지 않을까 싶어요.
> 
> String: final 클래스 StringUtils: 정적 필드와 정적 메서드만 담은 클래스

설명 감사합니다. 제가 이해한 의미가 맞는지 확인차 댓글 남깁니다. 혹시 그러면 final 클래스를 상속해서 메서드 추가를 못하니, final 클래스에 넣고 싶은 메서드들은 static 으로 만들어서 처리를 한다는 의미인가요?

**Comment by JamieShin0201** [comment]
> 설명 감사합니다. 제가 이해한 의미가 맞는지 확인차 댓글 남깁니다. 혹시 그러면 final 클래스를 상속해서 메서드 추가를 못하니, final 클래스에 넣고 싶은 메서드들은 static 으로 만들어서 처리를 한다는 의미인가요?

넵!! 맞습니다!! 궁금해서 StringUtils 클래스 주석을 읽어보니 아래와 같이 나와있네요!
> This class delivers some simple functionality that should really be provided by the core Java String and StringBuilder classes.
